# Basics of Tensor in Pytorch
- [Basics of Tensor in Pytorch](#basics-of-tensor-in-pytorch)
  * [import](#import)
  * [Creation of Tensor](#creation-of-tensor)
    + [torch.tensor(list, dtype=torch.dtype)](#torchtensor-list--dtype-torchdtype-)
    + [torch.arange(start, end, step)](#torcharange-start--end--step-)
    + [torch.zeros(), torch.ones()](#torchzeros----torchones--)
    + [torch.from_numpy()](#torchfrom-numpy--)
  * [Reshape Tensor](#reshape-tensor)
    + [torch.tensor.t() : transposition](#torchtensort-----transposition)
    + [torch.tensor.view()](#torchtensorview--)
  * [Tensor Extension](#tensor-extension)
    + [torch.cat()](#torchcat--)
    + [torch.stack()](#torchstack--)
  * [Arithmetic Operations With Tensor](#arithmetic-operations-with-tensor)

<small><i><a href='http://ecotrust-canada.github.io/markdown-toc/'>Table of contents generated with markdown-toc</a></i></small>


## import

In [65]:
import torch

## Creation of Tensor

### torch.tensor(list, dtype=torch.dtype)

In [66]:
# int16
a = torch.tensor([1], dtype=torch.int16)

# float
b = torch.tensor([2], dtype=torch.float32)

# double
c = torch.tensor([2], dtype=torch.float64)

a, b, c

(tensor([1], dtype=torch.int16),
 tensor([2.]),
 tensor([2.], dtype=torch.float64))

In [67]:
tensor_list = [a, b, c]
for t in tensor_list:
    print("Shape of tensor : {}".format(t.shape))
    print("dtype of tendor : {}".format(t.dtype))
    print("Device tensor is stored on {}".format(t.device))

Shape of tensor : torch.Size([1])
dtype of tendor : torch.int16
Device tensor is stored on cpu
Shape of tensor : torch.Size([1])
dtype of tendor : torch.float32
Device tensor is stored on cpu
Shape of tensor : torch.Size([1])
dtype of tendor : torch.float64
Device tensor is stored on cpu


### torch.arange(start, end, step)

In [68]:
a = torch.arange(10)
b = torch.arange(1, 10)
c = torch.arange(1, 10, 2)

a, b, c

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([1, 3, 5, 7, 9]))

### torch.zeros(), torch.ones()

In [69]:
zeros = torch.zeros(2)
ones  = torch.ones(2, 5, 3)
zeros, ones

(tensor([0., 0.]),
 tensor([[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]))

### torch.from_numpy() 

In [70]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6]])
y = torch.from_numpy(x)

x, y

(array([[1, 2, 3],
        [4, 5, 6]]),
 tensor([[1, 2, 3],
         [4, 5, 6]]))

## Reshape Tensor

### torch.tensor.t() : transposition

In [71]:
a = torch.arange(10).view(2, 5)

a, a.t()

(tensor([[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]),
 tensor([[0, 5],
         [1, 6],
         [2, 7],
         [3, 8],
         [4, 9]]))

In [80]:
a = torch.arange(1, 10).view(3, 3)
at = torch.transpose(a, 0, 1)  # swap bewten 0, 1 dims
at

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [78]:
a = torch.arange(1, 25).view(4, 3, 2)
at = torch.transpose(a, 0, 2)  # swap bewten 0, 2 dims
at

tensor([[[ 1,  7, 13, 19],
         [ 3,  9, 15, 21],
         [ 5, 11, 17, 23]],

        [[ 2,  8, 14, 20],
         [ 4, 10, 16, 22],
         [ 6, 12, 18, 24]]])

In [79]:
a = torch.arange(1, 25).view(4, 3, 2)
at = a.permute(2, 0, 1)  # swap elements E(i, j, k) to E(k, i, j)
at

tensor([[[ 1,  3,  5],
         [ 7,  9, 11],
         [13, 15, 17],
         [19, 21, 23]],

        [[ 2,  4,  6],
         [ 8, 10, 12],
         [14, 16, 18],
         [20, 22, 24]]])

### torch.tensor.view()

In [72]:
a1 = a.view(2, 5)

a1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [73]:
a2 = torch.arange(30).view(2, 5, 3)

a2

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11],
         [12, 13, 14]],

        [[15, 16, 17],
         [18, 19, 20],
         [21, 22, 23],
         [24, 25, 26],
         [27, 28, 29]]])

## Tensor Extension

### torch.cat()

In [59]:
a = torch.arange(1, 10).view(3, 3)
b = torch.arange(10, 19).view(3, 3)
c = torch.arange(19, 28).view(3, 3)

abc = torch.cat([a, b, c], dim=1)
abc, abc.shape

(tensor([[ 1,  2,  3, 10, 11, 12, 19, 20, 21],
         [ 4,  5,  6, 13, 14, 15, 22, 23, 24],
         [ 7,  8,  9, 16, 17, 18, 25, 26, 27]]),
 torch.Size([3, 9]))

In [62]:
a = torch.arange(1, 10).view(3, 3)
b = torch.arange(10, 19).view(3, 3)
c = torch.arange(19, 28).view(3, 3)

abc = torch.cat([a, b, c], dim=-2)
abc, abc.shape

(tensor([[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12],
         [13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]),
 torch.Size([9, 3]))

In [64]:
a = torch.arange(1, 10).view(3, 3)
b = torch.arange(10, 19).view(3, 3)
c = torch.arange(19, 28).view(3, 3)

abc = torch.cat([a, b, c], dim=0)
abc, abc.shape

(tensor([[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12],
         [13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]),
 torch.Size([9, 3]))

### torch.stack()

In [74]:
a = torch.arange(1, 10).view(3, 3)
b = torch.arange(10, 19).view(3, 3)
c = torch.arange(19, 28).view(3, 3)

abc = torch.stack([a, b, c], dim=1)
abc, abc.shape

(tensor([[[ 1,  2,  3],
          [10, 11, 12],
          [19, 20, 21]],
 
         [[ 4,  5,  6],
          [13, 14, 15],
          [22, 23, 24]],
 
         [[ 7,  8,  9],
          [16, 17, 18],
          [25, 26, 27]]]),
 torch.Size([3, 3, 3]))

In [75]:
a = torch.arange(1, 10).view(3, 3)
b = torch.arange(10, 19).view(3, 3)
c = torch.arange(19, 28).view(3, 3)

abc = torch.stack([a, b, c], dim=-2)
abc, abc.shape

(tensor([[[ 1,  2,  3],
          [10, 11, 12],
          [19, 20, 21]],
 
         [[ 4,  5,  6],
          [13, 14, 15],
          [22, 23, 24]],
 
         [[ 7,  8,  9],
          [16, 17, 18],
          [25, 26, 27]]]),
 torch.Size([3, 3, 3]))

In [76]:
a = torch.arange(1, 10).view(3, 3)
b = torch.arange(10, 19).view(3, 3)
c = torch.arange(19, 28).view(3, 3)

abc = torch.stack([a, b, c], dim=0)
abc, abc.shape

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],
 
         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]],
 
         [[19, 20, 21],
          [22, 23, 24],
          [25, 26, 27]]]),
 torch.Size([3, 3, 3]))

## Arithmetic Operations With Tensor

In [35]:
a = torch.arange(1, 10, 2)
b = torch.arange(10, 20, 2)

In [36]:
a + b

tensor([11, 15, 19, 23, 27])

In [37]:
a - b

tensor([-9, -9, -9, -9, -9])

In [49]:
# Multiply
a = torch.arange(10).view(2, 5)
b = 5
a * b

tensor([[ 0,  5, 10, 15, 20],
        [25, 30, 35, 40, 45]])

In [50]:
# Matrix Multiply
a = torch.arange(10).view(2, 5)
b = torch.arange(2, 22, 2).view(5, 2)

torch.matmul(a, b)

tensor([[140, 160],
        [390, 460]])

In [52]:
# Elementwise Multiply
a = torch.arange(10).view(2, 5)
b = torch.arange(2, 22, 2).view(2, 5)

torch.mul(a, b)

tensor([[  0,   4,  12,  24,  40],
        [ 60,  84, 112, 144, 180]])